# Generated by registream/tools/render_citations.py -- DO NOT EDIT BY HAND.
#
# Edit registream/citations.yaml, then run
#   python tools/render_citations.py write-r
# from the registream/ repo root.

.CITATION_WORK_KEY    <- "registream"
.CITATION_TITLE       <- "RegiStream: Infrastructure for Register Data Research"
.CITATION_SHORT_TITLE <- "Infrastructure for Register Data Research"
.CITATION_URL         <- "https://registream.org"
.CITATION_YEAR        <- "2024"
.CITATION_BIBTEX_KEY  <- "clark2024registream"
.CITATION_AUTHORS_APA <- "Clark, J. & Wen, J."

.CITATION_APA                      <- "Clark, J. & Wen, J. (2024). RegiStream: Infrastructure for Register Data Research. https://registream.org"
.CITATION_APA_VERSIONED_TEMPLATE   <- "Clark, J. & Wen, J. (2024). RegiStream: Infrastructure for Register Data Research (Version %s). Available at: https://registream.org."
.CITATION_BIBTEX_PLAIN             <- "@software{clark2024registream,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{RegiStream: Infrastructure for Register Data Research}},\n  year    = {2024},\n  url     = {https://registream.org}\n}"
.CITATION_BIBTEX_VERSIONED_TEMPLATE <- "@software{clark2024registream,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{RegiStream: Infrastructure for Register Data Research}},\n  version = {{{VERSION}}},\n  year    = {2024},\n  url     = {https://registream.org}\n}"
