"""Generated by registream/tools/render_citations.py. DO NOT EDIT BY HAND.

Edit registream/citations.yaml, then run `python tools/render_citations.py write-python`.
"""

from __future__ import annotations

WORK_KEY = 'registream'
TITLE = 'RegiStream: Infrastructure for Register Data Research'
SHORT_TITLE = 'Infrastructure for Register Data Research'
URL = 'https://registream.org'
YEAR = '2024–'
BIBTEX_KEY = 'clark2024registream'
AUTHORS_APA = 'Clark, J. & Wen, J.'

APA = 'Clark, J. & Wen, J. (2024–). RegiStream: Infrastructure for Register Data Research. https://registream.org'
APA_VERSIONED_TEMPLATE = 'Clark, J. & Wen, J. (2024–). RegiStream: Infrastructure for Register Data Research (Version {version}). Available at: https://registream.org.'
BIBTEX_PLAIN = '@software{clark2024registream,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{RegiStream: Infrastructure for Register Data Research}},\n  year    = {2024--},\n  url     = {https://registream.org}\n}'
BIBTEX_VERSIONED_TEMPLATE = '@software{clark2024registream,\n  author  = {Clark, Jeffrey and Wen, Jie},\n  title   = {{RegiStream: Infrastructure for Register Data Research}},\n  version = {{{VERSION}}},\n  year    = {2024--},\n  url     = {https://registream.org}\n}'
